version: '3'
services:
  server:
    build: server
    ports:
     - "8000:8000"
    env_file:
      - .env.local
    volumes:
      - ./server:/usr/src/app/
  tg-bot:
    build: services/tg_bot
    restart: always
    ports:
      - "8081:8081"
    env_file:
      - .env.local
    volumes:
      - ./services/tg_bot:/usr/src/tg_bot/